### ISSUE TITLE
a error in evnet

### ISSUE THREAD

**Issue by ghost** [rep/evnet#8]
When i install  mhn,it occured a error.I can't figure out what happened.
So i come here to find help.

Errors:
- pip install -e git+https://github.com/rep/evnet.git#egg=evnet-dev
  Obtaining evnet from git+https://github.com/rep/evnet.git#egg=evnet-dev
  Cloning https://github.com/rep/evnet.git to ./env/src/evnet
  Collecting pyev>=0.5.3-3.8 (from evnet)
  Using cached pyev-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z7NHFh/pyev/setup.py", line 56, in <module>
        check_version(python_version, min_python_versions[major], "Python{0}".format(major))
      File "/tmp/pip-build-z7NHFh/pyev/setup.py", line 40, in check_version
        if StrictVersion(current_version) < StrictVersion(minimum_version):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in **init**
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '2.7.11+'
  ---
  
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z7NHFh/pyev/

**Comment by zam89** [comment]
Guys, any update on this? I got same problem.

**Comment by ghost** [comment]
@zam89  NO!
